# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pphbRBwjvWkgdpNmRY09Qvp4VIFbs5rg

Codigo base para aprender a programr pyton. | Datos (Alimento) Sentencias ( Procesamientos)
"""

primera_variable = 12

"""
Modificar el valor de la variable
```
# Modificas el Numero para cambiar el valor de la variable. Y el nombre de la variable para asignarle otro nombre al nuemro de la variable.
```

"""

primera_variable

print (primera_variable)

""" Codigo = primera_variable y print (primera_variable) te da siempre el resultado del dato/s que tengas como resultados en las variables.
```
# Codigo = primera_variable y print (primera_variable)
```
"""

print ("Hola aprendiz")
print (primera_variable)

"""En este caso añadimos un print ("Hola aprendiz") que nos da como respuesta lo que tengamos escrito (en este caso Hola aprendiz) esto lo podemos modificar para darnos una información como puede ser (Resultado de tu primera variable)
Y añadimos abajo el print para que nos de el resultado de la primera variable.
```
# Codigo = print ("Hola aprendiz") & print (primera_variable)
```
"""

variable1 = 100
Variable2 = 50
Variable3 = "pepe"

"""En este caso añadimos nuevas variables. En el caso de Variable3 añadimos un nombre y al ser nombre este va entre "" (Comillas)"""

print (primera_variable,variable1,Variable2,Variable3)

"""A traves de un print le pedimos que nos de los resultados de la primera variable que creamos asi como de la variables añadidas anteriormente."""

MiVariable1 = 2
mivariable = 2

"""Pyton es capaz de identificar variables con el mismo nombre. Si las variables tienen el mismo resultado da igual si esta en mayusculas o minusculas. Simpre te dara el mismo resultado en un Print pero si el resultado es distinto es capaz de diferenciarlo."""

